project/config/routes.rb
Rails.application.routes.draw do
  resources :sitems
  resources :starfolds
  devise_for :users
  resources :users
  resources :orders
  resources :items
  resources :carts
  get 'store/index'
  resources :products 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root :to => 'store#index', :as => 'store'
end

project/app/models/sitem.rb
class Sitem < ApplicationRecord
    belongs_to :product
    belongs_to :starfold
end

project/app/controllers/sitems_controller.rb
class SitemsController < ApplicationController
  before_action :set_sitem, only: %i[ show edit update destroy ]
  before_action :authenticate_admin, only: %i[  ]

  # GET /sitems or /sitems.json
  def index
    @sitems = Sitem.all
  end

  # GET /sitems/1 or /sitems/1.json
  def show
  end

  # GET /sitems/new
  def new
    @sitem = Sitem.new
  end

  # GET /sitems/1/edit
  def edit
  end

  # POST /sitems or /sitems.json
  def create
    @starfold = current_starfold
    product = Product.find(params[:product_id])
    # @item = @cart.add_product(product.id)
    @sitem = @starfold.add_product(product.id)

    respond_to do |format|
      if @sitem.save
        format.html { redirect_to @sitem.starfold, notice: "Sitem was successfully created." }
        format.json { render :show, status: :created, location: @sitem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sitems/1 or /sitems/1.json
  def update
    respond_to do |format|
      if @sitem.update(sitem_params)
        format.html { redirect_to sitem_url(@sitem), notice: "Sitem was successfully updated." }
        format.json { render :show, status: :ok, location: @sitem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sitems/1 or /sitems/1.json
  def destroy
    @sitem.destroy

    respond_to do |format|
      format.html { redirect_to current_starfold, notice: "Sitem was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sitem
      @sitem = Sitem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sitem_params
      params.require(:sitem).permit(:product_id, :starfold_id)
    end
end

project/app/helpers/sitems_helper.rb
module SitemsHelper
end

project/app/views/sitems/_form.html.erb
<%= form_with(model: sitem) do |form| %>
  <% if sitem.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sitem.errors.count, "error") %> prohibited this sitem from being saved:</h2>

      <ul>
        <% sitem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.number_field :product_id %>
  </div>

  <div>
    <%= form.label :starfold_id, style: "display: block" %>
    <%= form.number_field :starfold_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project/app/views/sitems/_sitem.html.erb
<div id="<%= dom_id sitem %>" class="entry">
  <div class='entry_image'>
      <%= image_tag(sitem.product.image_url) %>
  </div>
  <div class='entry_info'>
      <div class="title_line"><%= sitem.product.title %></div>
      <div class='des_line'>
          <div class='des_content'>
              <%= sanitize(sitem.product.description) %>
          </div>
      </div>
      <div class="price_line">
          <span class="price">价格：<%= sitem.product.price %> 元</span>
          
      </div>
  </div>
  <div class='entry_option'>
      <div class="cart_line line_item">
          <%= button_to '加入购物车',items_path(product_id: sitem.product) %>
      </div>
      <div class="star_line line_item">
          <!--
            <%= button_to '取消收藏',sitems_path(product_id: sitem.product) %>
          -->
          <%= button_to "取消收藏", sitem, method: :delete %>
      </div>
  </div>
  <div class="entry_button">
      <%= button_to '查看商品详情', sitem.product , method: :get %>
  </div>
</div>

project/app/views/sitems/edit.html.erb
<h1>Editing sitem</h1>

<%= render "form", sitem: @sitem %>

<br>

<div>
  <%= link_to "Show this sitem", @sitem %> |
  <%= link_to "Back to sitems", sitems_path %>
</div>

project/app/views/sitems/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sitems</h1>

<div id="sitems">
  <% @sitems.each do |sitem| %>
    <%= render sitem %>
    <p>
      <%= link_to "Show this sitem", sitem %>
    </p>
  <% end %>
</div>

<%= link_to "New sitem", new_sitem_path %>

project/app/views/sitems/new.html.erb
<h1>New sitem</h1>

<%= render "form", sitem: @sitem %>

<br>

<div>
  <%= link_to "Back to sitems", sitems_path %>
</div>

project/app/views/sitems/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sitem %>

<div>
  <%= link_to "Edit this sitem", edit_sitem_path(@sitem) %> |
  <%= link_to "Back to sitems", sitems_path %>

  <%= button_to "Destroy this sitem", @sitem, method: :delete %>
</div>