project/config/routes.rb
Rails.application.routes.draw do
  resources :sitems
  resources :starfolds
  devise_for :users
  resources :users
  resources :orders
  resources :items
  resources :carts
  get 'store/index'
  resources :products 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root :to => 'store#index', :as => 'store'
end

project/app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :items, dependent: :destroy

    def add_product(product_id)
        current_item = items.find_by_product_id(product_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = items.build(:product_id => product_id)
        end
        current_item
    end

    def total_price
        items.to_a.sum{ |item| item.total_price }
    end
end

project/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  before_action :authenticate_admin, only: %i[ index ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url, notice: "您的购物车已清空" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

project/app/helpers/carts_helper.rb
module CartsHelper
end

project/app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>" class="cart_content_one">
    <div class="content_head">
        <div class="head_title">总价：</div>
        <div class="head_item"><%= @cart.total_price %></div>
    </div>

    <div class="content_form">
        <%= render cart.items %>
    </div>
</div>

project/app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project/app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

project/app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

project/app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

project/app/views/carts/show.html.erb
<div class="main_cart">

  <!--
  <p style="color: green"><%= notice %></p>
  -->

  <div class="cart_bar">
  <!--
    <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
    <%= link_to "Back to carts", carts_path %>
  -->
    <div class="bar_title">
      我的购物车
    </div>

    <div class="bar_options">
      <div class="common_button green_button">
        <%= button_to "清空购物车", @cart, method: :delete %>
      </div>
      <div class="common_button yellow_button">
        <%= button_to "结算", new_order_path, method: :get %>
      </div>
      
    </div>

    
  </div>

  <div class="cart_content">
    <%= render @cart %>
  </div>

</div>