project/config/routes.rb
Rails.application.routes.draw do
  resources :sitems
  resources :starfolds
  devise_for :users
  resources :users
  resources :orders
  resources :items
  resources :carts
  get 'store/index'
  resources :products 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root :to => 'store#index', :as => 'store'
end

project/app/models/product.rb
class Product < ApplicationRecord

    PRODUCT_TYPES = ["办公设备", "地方特产", "护理清洁", "家用电器", "粮油调味", "生活日用", "新鲜水果", "运动鞋包"]

    has_many :items
    has_many :sitems
    before_destroy :ensure_not_referenced_by_any_item, :ensure_not_referenced_by_any_sitem

    validates :title, :description, :product_type, :image_url, :presence => true
    validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
    validates :title, :uniqueness => true
    validates :product_type, :inclusion => PRODUCT_TYPES
    validates :image_url, format: {
        with:    %r{\.(gif|jpg|png)\z}i,
        message: '应为gif,png或jpg格式图片'
    }


    private

        def ensure_not_referenced_by_any_item
            unless items.empty?
                errors.add(:base, 'Items present')
                throw :abort
            end
        end

        def ensure_not_referenced_by_any_sitem
            unless sitems.empty?
                errors.add(:base, 'Items present')
                throw :abort
            end
        end
end

project/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_admin, only: %i[ index new edit destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to store_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :product_type, :description, :image_url, :price)
    end
end

project/app/helpers/products_helper.rb
module ProductsHelper
end

project/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <div class="fielder fadeIn first error">
    <% if product.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="fielder fadeIn second">
    <%= form.label "商品名称", class: "label", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="fielder fadeIn second lineline">
    <%= form.label "商品类型", class: "label", style: "display: block" %>
    <%= form.select :product_type, Product::PRODUCT_TYPES, prompt: '请选择商品类型' %>
  </div>

  <div class="fielder fadeIn third">
    <%= form.label "详情描述", class: "label", style: "display: block" %>
    <%= form.text_area :description, :rows => 6 %>
  </div>

  <div class="fielder fadeIn third">
    <%= form.label "图片链接", class: "label", style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div class="fielder fadeIn fourth">
    <%= form.label "商品价格", class: "label", style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div class="fadeIn fourth">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="product_main_one">

  <div class="product_info">
    <div class="info_image">
      <%= image_tag(product.image_url) %>
    </div>
    <div class="info_lines">
      <div class="title_line">
        <%= product.title %>
      </div>
      <div class="type_line">
        <%= product.product_type %>
      </div>
      <div class="price_line">
        <span class="price">价格：<%= product.price %> 元</span>
      </div>
    </div>

  </div>

  <div class="product_description">
    <div class="title">
      商品详情
    </div>
    <%= product.description %>
  </div>
  

</div>

project/app/views/products/edit.html.erb
<!--
<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>-->

<div class="main_form">

  <div class="wrapper fadeInDown">
    <div id="formContent">
      <h2 class="active">编辑商品 </h2>

      <%= render "form", product: @product %>

      <br>
    </div>
  </div>
</div>

project/app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <p>
      <strong>Title:</strong>
      <%= product.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= truncate(strip_tags(product.description), length:80) %>
    </p>

    <p>
      <strong>Image:</strong>
      <%= image_tag(product.image_url, :class => 'list_image') %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= product.price %>
    </p>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

project/app/views/products/new.html.erb
<div class="main_form">

  <div class="wrapper fadeInDown">
    <div id="formContent">
      <h2 class="active">新增商品 </h2>

      <%= render "form", product: @product %>

      <br>
    </div>
  </div>
</div>
<!--
<div>
  <%= link_to "Back to products", products_path %>
</div>-->

project/app/views/products/show.html.erb
<div class="main_product">

<div class="product_main">
  <%= render @product %>
</div>
<div class="product_options">

  <% if user_admin? %>
    <div class="common_button blue_button">
      <%= button_to "编辑商品", edit_product_path(@product), method: :get %> 
    </div>
    <div class="common_button red_button">
      <%= button_to "下架商品", @product, method: :delete %>
    </div>
  </div>
  <% else %>
    <div class="common_button green_button">
      <%= button_to '加入购物车',items_path(product_id: @product) %>
    </div>
    <div class="common_button yellow_button">
      <%= button_to '收藏', sitems_path(product_id: @product) %>
    </div>
  <% end %>
  
</div>


</div>